# Generated by Django 5.2 on 2026-05-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_viaje', models.DateField(verbose_name='Fecha del viaje')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('cantidad_asientos', models.PositiveIntegerField(verbose_name='Cantidad de asientos')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de reserva')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto total')),
                ('pagado', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='rutas.salida')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-creado'],
            },
        ),
    ]
