# Generated by Django 5.2 on 2026-09-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_cliente'),
        ('rutas', '0002_ruta_imagen_salida_precio_promocional_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['-creado'], name='reserva_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['salida', 'estado'], name='reserva_salida_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_asientos__gte', 1)), name='reserva_cantidad_asientos_min_1'),
        ),
    ]
