# Generated by Django 5.2 on 2026-09-28 23:11

import configuracion.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text='Identificador tecnico que usa el sitio. No lo cambies si ya esta en uso.', max_length=60, unique=True, verbose_name='Clave')),
                ('titulo', models.CharField(help_text='Para identificar la sección en el admin.', max_length=100, verbose_name='Título')),
                ('imagen', models.ImageField(blank=True, help_text=' JPG, PNG o WEBP, hasta 8 MB. Se usa de fondo y se recorta a la sección.', upload_to='sitio/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), configuracion.models.validar_tamano], verbose_name='Imagen')),
                ('alt_imagen', models.CharField(blank=True, help_text='Describe la imagen para lectores de pantalla y buscadores.', max_length=200, verbose_name='Texto alternativo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible en el sitio')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Contenido del sitio',
                'verbose_name_plural': 'Contenidos del sitio',
                'ordering': ['orden', 'clave'],
            },
        ),
    ]
