# Generated by Django 5.2 on 2026-06-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rutas/'),
        ),
        migrations.AddField(
            model_name='salida',
            name='precio_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio promocional'),
        ),
        migrations.AddField(
            model_name='salida',
            name='promocion_activa',
            field=models.BooleanField(default=False),
        ),
    ]
