# Generated by Django 5.2 on 2026-09-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
        ('rutas', '0002_ruta_imagen_salida_precio_promocional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, help_text='Asientos que se pueden vender en esta salida. Vacio = sin control de capacidad. Se hereda del vehiculo asignado al crearse.', null=True, verbose_name='Capacidad (asientos)'),
        ),
        migrations.AddConstraint(
            model_name='salida',
            constraint=models.CheckConstraint(condition=models.Q(('precio_base__gte', 0)), name='salida_precio_base_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='salida',
            constraint=models.CheckConstraint(condition=models.Q(('precio_promocional__gte', 0), ('precio_promocional__isnull', True), _connector='OR'), name='salida_precio_promocional_no_negativo'),
        ),
    ]
