# Generated by Django 5.2 on 2026-09-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_salida_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, help_text='Asientos que se pueden vender en esta salida. Si la dejes vacia se toma la del vehiculo al crearla. Vacio = sin control de plazas.', null=True, verbose_name='Capacidad (asientos)'),
        ),
    ]
