# Generated by Django 5.2 on 2026-06-03 23:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vto', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('en_cartera', 'En cartera'), ('depositado', 'Depositado'), ('rechazado', 'Rechazado'), ('entregado', 'Entregado')], default='en_cartera', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.cliente', verbose_name='Cliente')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.pago', verbose_name='Pago asociado')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'ordering': ['-fecha_emision', '-creado'],
            },
        ),
    ]
