# Generated by Django 5.2 on 2026-05-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flota', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('origen', models.CharField(max_length=200, verbose_name='Origen')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('fecha_viaje', models.DateField(verbose_name='Fecha del viaje')),
                ('cantidad_pasajeros', models.PositiveIntegerField(verbose_name='Cantidad de pasajeros')),
                ('comentarios', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cotizado', 'Cotizado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('precio_cotizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio cotizado')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas solo para el admin')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio', verbose_name='Tipo de servicio')),
                ('tipo_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.vehiculo', verbose_name='Tipo de vehículo preferido')),
            ],
            options={
                'verbose_name': 'Solicitud de viaje',
                'verbose_name_plural': 'Solicitudes de viaje',
                'ordering': ['-creado'],
            },
        ),
    ]
