# Generated by Django 5.2 on 2026-05-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('van', 'Van'), ('minibus', 'Minibús'), ('bus', 'Bus')], max_length=20)),
                ('capacidad', models.PositiveIntegerField(help_text='Cantidad máxima de pasajeros')),
                ('patente', models.CharField(max_length=20, unique=True, verbose_name='Patente')),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la web')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Flota',
                'ordering': ['orden'],
            },
        ),
    ]
